title: "SCHOI1337"  
description: "Exploring cybersecurity and ethical hacking through hands-on practice, research, and quiet persistence."
baseurl: "" 
url: "https://schoi1337.github.io" 

markdown: kramdown
highlighter: none
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# Build settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: page

# Site Settings
timezone: Australia/Melbourne
