title: "SCHOI1337"  
description: "Exploring cybersecurity and ethical hacking through hands-on practice, research, and quiet persistence."
baseurl: "" 
url: "https://schoi1337.github.io" 


highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter: nil
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# Build settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      highlighter: none
      markdown: kramdown
      kramdown:
        syntax_highlighter_opts:
          block:
            template: code_block
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: page

# Site Settings
timezone: Australia/Melbourne
